### ISSUE TITLE
Conf Cleanup

### ISSUE THREAD

**Issue by exoscoriae** [exoscoriae/eXoDOS#1095]
All leftover conf files inside game exe's have been removed.

**Comment by Python-Exoproject** [comment]
I was surprised this was actioned but as it was I did a scan using TC to see if any were overlooked. A couple still show (though mostly from custom dosbox builds), and another that has an unused dosbox folder I found during the scan:

Hong Gildong-jeon 2: Has an unused Dosbox folder in the zip which can be deleted. As a further note the game isnt cracked which ill make a separate bug report for.

Mike Gunner (1988): This game uses a custom dosbox build. In the custom dosbox folder there is an unused dosbox.conf. You may have left this one on purpose due to the custom dosbox build? 

Mino's Adventure (1997): Similar to above this is a custom dosbox game. There are two unused dosbox.conf files, one is definitely removable from the main game folder, the other is part of the custom dosbox folder and may have been left deliberately? Since your already cleaning this zip up there is also a .url file

Psycho Killer (1993): Has an unused Dosbox folder in the zip which includes a conf file. Also has a file "start.bat" which is an old unused dosbox launch bat file.

Sierra Network, The (1991): Unused dosbox.conf in zip

System Shock (1994): Inside the zip \systemsh\ssp\res folder there are three versions of dosbox in folders ECE, Dosbox, and Gulikoza. May have been left deliberately as they were part of the SSP package?

Wizardry VI - Bane of the Cosmic Forge (1990): Another custom dosbox build so you probably left the dosbox.conf alone deliberately.

**Comment by exoscoriae** [comment]
caught the few missed ones and left the deliberate ones. thanks for scanning
