### ISSUE TITLE
The Games: Winter Challenge (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1193]
The game asks for a coded wheel number when I select an event, and back to dos.

**Comment by exoscoriae** [comment]
cracked

**Comment by Python-Exoproject** [comment]
Just an FYI. I didnt have the copy protection show up in the version we had before. I am concerned about changes to this one due to a conversation I had with @SmilingSpectre. He said:

"Smiling Spectre 02/07/2020
there is interesting discussion at the Abandonia about Winter Challenge. Basically, people claims that game is not cracked/cracked wrong. Can we check our version somehow? (I am bad in sports arcade, so I cannot check myself)."

Abandonia is down right now so I will sum up that they discussed that there is a crack out there that makes achieving wins much easier and in record setting times. There also seems to be a bug in the speed skating on the third lap, but thats possibly even in the original. I replied to Spectre that I obtained our current copy for us in December, that it is cracked, but that I didnt know where I got it from. I tested it a bit and it didnt seem to easy, that or I just really sucked.

Ive tried this new crack and didnt see any differences to the version we had before, but I just dont know with this game whether my crack, or this new crack are best. Hell they were quite vague in the forum discussion though there were many people agreeing with each other, so maybe there isnt even an issue in the first place.

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject on mobygames there is an entry for ["Summer & Winter: Olympic Challenge"](https://www.mobygames.com/game/dos/summer-winter-olympic-challenge_), a compilation of both games
and in the trivia it says:
"For this compilation the copy protection was "removed". Each of the games provides a .com file of the same name as the .exe file which will disable the copy protection at runtime - so if you start the .exe file directly you will still get the copy protection screens. Starting the games as intended from the CD's root directory will use the correct version of course."

maybe helpful?

**Comment by Python-Exoproject** [comment]
Thanks @TimberlAndRE-de. As thats an official release that was cracked by them I feel more confident with that. @exoscoriae Comparing that CD compilation release to our version it looks like the winter.com you are using is from that CD which is great, but the exe is not the same. I suggest using the exe from the CD Timber posted in our version and call it a day.

**Comment by exoscoriae** [comment]
added cd iso to both games. replaced winter exe and files.

**Comment by SmilingSpectre** [comment]
It was not "crack is easier", but just opposite "crack is not work as intended, making game _harder_". *shrug* Well, no use to argue about it as I am too bad in this game anyway. Man on Abandonia seriously intended to look into the issue, so I'll tell if you'll get something. And nothing for now. :)

**Comment by Python-Exoproject** [comment]
@exoscoriae I am reactivating due to further information. @SmilingSpectre has reported a user from abandonia confirmed that using a fresh copy from archive.org and the code wheel the game works as expected. The same user complained that no other copy works without triggering the copy protection that causes bugs. 

Here http://www.abandonia.com/vbullet/showthread.php?t=109&page=8 there is a statement that the .com that comes with the CD compilation still causes the issue. Maybe Kudgel can take a look and see what he thinks now that someone is saying that the com we thought solved the issue is still not working?

In the meantime maybe we should switch bag to a vanilla copy and leave it uncracked with a note to use the recently acquired codewheel? I believe the same will apply to "The Games: Summer Challenge (1992)" #1177

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject generally we have the codewheel images, but they're ugly as f... , so I didn't create the interactive one yet:

![RING1](https://user-images.githubusercontent.com/67441153/111466622-ce51bb00-8723-11eb-9bc0-21d1635247b0.png)
![RING2](https://user-images.githubusercontent.com/67441153/111466626-ceea5180-8723-11eb-82b5-a330efb0a166.jpg)
![RING0](https://user-images.githubusercontent.com/67441153/111466627-cf82e800-8723-11eb-9a86-7594d18c9c70.png)

**Comment by exoscoriae** [comment]
until we have a functioning codewheel, reversion seems like a bad ideas.

**Comment by TimberlAndRE-de** [comment]
found the code wheel (#3149 )

**Comment by exoscoriae** [comment]
so, the winter games archive has an ISO in it from 1996 that includes both games. Do we know if this iso is actually good? I remember there being discussion that a later cd release was precracked, making the games impossible on that release.

**Comment by exoscoriae** [comment]
switched game to use standard exe instead of cracked com file
