### ISSUE TITLE
Battlecruiser 3000AD (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#144]
has watermark replacementdocs
seems typed-down or text-recognized and coverted to text

**Comment by SmilingSpectre** [comment]
It's deformed by replacementdocs indeed. But as you can see right at the start, it's 2.0. Windows version. And docs taken right from the CD.

I uploaded full doc pack, but I am not exactly sure that it will work for DOS version.

**Comment by TimberlAndRE-de** [comment]
thx, added to github as quality-upgrade

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] manual (current one is a "preview manual" v2.0 as you can see on the note on the cover page and described above, this seems to be the earlier version for the DOS version ... maybe add both, one as an alternate manual in extras?)

added to the github folder

**Comment by SmilingSpectre** [comment]
It's a scanned manual, but looks somewhat suspicious for me. Basically, because it failed to print " character in text. All quote characters was replaced with... well, it's better to show.

![image](https://user-images.githubusercontent.com/24454178/231143956-97a0b84f-551d-4ca2-b6b2-a24720b1b781.png)

It happens in any use of ` and ´ (and all 's spelled initially as ´s looks weird in result). Maybe typo. Maybe someone printed e-docs and scanned them. *shrug*

**Comment by exoscoriae** [comment]
I don't believe this is very useful in this state...?

**Comment by exoscoriae** [comment]
added as alternate manual
