### ISSUE TITLE
Winnie the Pooh in the Hundred Acre Wood (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1696]
Meant to work in Tandy mode but only shows Black and White. @SmilingSpectre has found a .tc image and asked @boohyaka to have a look.

**Comment by Python-Exoproject** [comment]
@SmilingSpectre has started a discussion with New Rising Sun about getting a working copy sorted.

**Comment by exoscoriae** [comment]
NRS reached out to me with the decryptor tool as well as a previously decrypted copy of the game.

His exact message read:
"Sierra's encryption routine padded the image to the next 512 byte boundary, and then also added an EOF byte (1A). So be sure to run "unp l -r" after decryption to get the proper .EXE size.

Also keep in mind that MAINJR.EXE is unsafe to be run directly, because the risk is that it will be loaded to a memory position where the PCjr's video memory gets in the way. So even if you decrypt MAIN.EXE and MAINJR.EXE, you still need to use the WINNIE.COM loader, with the keydisk check and file decryption patched-out of course. This archive contains the complete game, with decrypted-and-trimmed MAIN(JR).EXE and the patched WINNIE.COM. You will still need to mount the directory to the A drive, because both the loader and the MAIN(JR).EXE hard-code the A drive in their filenames."

Currently I'm still running into issues with the game. While it starts in PCjr mode, it never gets passed the first screen. debug logs reveal multiple unhandled op error codes. Still looking into it.

**Comment by exoscoriae** [comment]
[DECRYPT.ZIP](https://github.com/exoscoriae/eXoDOS/files/5124335/DECRYPT.ZIP)

This is the decryption tool he wrote.

**Comment by exoscoriae** [comment]
loadfix -88 fixes it
