### ISSUE TITLE
Maniac Mansion (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1893]
found an original hint book as an extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
ArkhangelAzrael found an extra:
- [ ] Game Design Document
added to the github folder

- [ ] and the Quick Reference card has a watermark "replacementdocs", should be removed

**Comment by exoscoriae** [comment]
also removed watermark from Bulletin Board pdf

**Comment by Eulisker** [comment]
I found a better looking 

- [ ] Reference Card

also

- [ ] Hintbook Ad
- [ ] Registry Card

and lastly another 

- [ ] codebook. 

The one currently in the collection seems to be for the later release. Here is a photo of the earliest pc release contents.

![imageview](https://user-images.githubusercontent.com/81642149/126307364-8075732a-e12d-455e-8227-9fded2b3cf4d.jpg)
[source](https://ogdb.eu/index.php?section=game&gameid=4367)

Added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I scanned (or rather someone scanned for me) the Hintbook and i put it together to a bunch of pdfs:

- [ ] Hintbook
- [ ] Hintbook (revealed)
- [ ] Hintbook Map

The map is in the middle of the book but in the wrong orientation to read it. This was the best way to have it in a readable form and still part of the hintbook.
I played with the contrast and brightness of the revealed version to make it more readable and left the not revealed version as is. If you want to change something there please tell me.

Two notes for the extras of this version:

- Restored Artwork by Laserschwert - Poster (No Title).jpg  This should probably be (No Logo) or something like that. The difference between this and the (No Text) is the LucasFilm Games Logo.
- The video of the Demo should probably be moved to the Enhanced Version since it shows the Enhanced Version.
