### ISSUE TITLE
Spelling Fun One (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1922]
Beginning of launch bat looks like this:

@set var=%cd%
for %%I in (.) do set GameDir=%%~nxI
@echo off
..\\..\\..\\util\setconsole.exe /minimize
cd ..
cd ..
cd ..

instead of this:

@echo off
..\\..\\..\\util\setconsole.exe /minimize
@set var=%cd%
for %%I in (.) do set GameDir=%%~nxI
cd .. 
cd .. 
cd ..

**Comment by exoscoriae** [comment]
I don't see how this was possible. Every time I modify an install file, I wholesale replace every single install file in every single folder.

As I just removed the extra ":next" tag the other day, this issue is already impossible for me to check as the file has been updated since then. 

Even so, I don't understand how one install file could be different when i use a batch file that copies the new install.bat file to every single folder.

/shrug

**Comment by Python-Exoproject** [comment]
Launch bat file, not install bat file :-)

**Comment by exoscoriae** [comment]
thanks. I guess it wasn't hurting anything, but it is nice to have it normalized

**Comment by Python-Exoproject** [comment]
The issue is more about the where the echo off is as its displaying things to the user we usually dont. In the current version you just uploaded it is all fixed except for the fact @echo off is missing from the top of the file meaning its outputting every line twice along with command prompts. Add "@echo off" at top to fix.
