### ISSUE TITLE
Spellcasting 201 - The Sorcerers Appliance (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1928]
found the hint book

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found better looking scans of the

- [ ] Map
- [ ] Registration Form

The Map is an actual scan instead of the photo currently in the collection. You can see the seems where the final document was put together out of a few different scans. But i still think it is of overall higher quality than the current version.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found a higher quality 

- [ ] Map

Added to the github folder.
