### ISSUE TITLE
Quasar (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1991]
Currently cant turn to the right in game at all. I suspect its partly to do with cycles as when set to around 300 you can get a sluggish response to turn right, but the game is a bit to slow at this speed and when I say sluggish, I mean alternate between holding the right key down for a bit and rapidly tapping it to eventually get some movement in that direction. There is probably more to it than just cycles. I do note that joystick is set to 4axis but if its anything else there is no response in game. Maybe something you would like to take a crack at @SmilingSpectre?

**Comment by exoscoriae** [comment]
moving to low priority as this is not likely something that will be fixed any time soon.

**Comment by exoscoriae** [comment]
another game that can be tackled by someone who enjoys messigg with BASIC

**Comment by Thraka** [comment]
Where can I get a copy to work on?

**Comment by SmilingSpectre** [comment]
In the collection. ExoDOS5 has it.

**Comment by Thraka** [comment]
Ahh yes, my mistake. I spent an hour or two playing around with this and I came to these conclusions:

1. Tandy mode seems to crash with this game if you use a 2axis stick in the config. There must be something where it wants 4axis at all times to see 2 joysticks connected.
2. DOSBox is terrible at assigning AXIS to joysticks...
3. The problem really is that DOSBox remaps the AXIS all over the place. One time my right-stick (axis 2,3) was mapped to the tandy stick 0,1.. Then another time axis 3 and axis 5 (a shoulder trigger) was mapped to tandy stick 0,1..
4. Keyboard input is too slow

   I recoded the game to use keyboard instead of the joystick but the game is unplayable. Considering you can only have 1 key pressed at a time you can't really navigate around like you would with a joystick. Unfortunately the coder didn't use good BASIC line numbers and  you can't really inject anything anywhere. There's a possibility that you could add in `ON KEY` commands to trap the keyboard instead of reading `INSTR$`, but there's no place free line numbers to inject that logic. Re-line numbering the code would be too time consuming and easily open it for bugs.

Here's my modified code for the record. I put `REM THRAKA` on lines that I duplicated and edited.
[quasar2.zip](https://github.com/exoscoriae/eXoDOS/files/13221605/quasar2.zip)

**Comment by exoscoriae** [comment]
@Thraka Thank you for this. However, I was unable to get any response. What keys did you assign to work in the game? It just sits at the title screen for me.

**Comment by exoscoriae** [comment]
seems f1 starts the game
