### ISSUE TITLE
After Burner (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2003]
Can do Tandy sound. Its one of the ones that while it has Tandy sound it also has as a separate option VGA graphics so will need user choice instead of just switching. Good news is the same settings work for both so we can set it up using the "-machine tandy" command line option. Cycles are running a bit fast so reduce to cycles=1200 which works for both versions. Its also one of the games that presents you in game with a selection for graphics mode so there will need to be a user note saying "select VGA from in game menu if you choose VGA here, or Tandy (16 colour) if you choose Tandy here". I specified the 16 colour as there is two Tandy options, one 4 colour the other 16 colour.

**Comment by exoscoriae** [comment]
decided to just have it launch abtdy  using a tandy.conf file, that way the user doesn't have to choose tandy twice.

thing is, tandy 16 color doesn't seem any better than vga 16 color. VGA should be 256 color... so I have no idea what that is all about.

actually, I just confirmed = launching the VGA option just launches the ega exe. so ega and vga are identical in this case.

I kept the option to not be forced into tandy only though, just because it sounds different.

**Comment by TimberlAndRE-de** [comment]
not really a bug since the game runs without problems, but in the options menu (for me) there is an error when starting After Burner because of the "&" in the options text:
`echo Press 1 to play After Burner using IBM (CGA & EGA)`

leeds to an 

changing it to
`echo Press 1 to play After Burner using IBM (CGA ^& EGA)`
works for me

**Comment by exoscoriae** [comment]
good catch and fix.

**Comment by Python-Exoproject** [comment]
In the updater?

**Comment by exoscoriae** [comment]
yes, it is in the updater
