### ISSUE TITLE
The Hunt for Red October (1987)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2006]
Can do Tandy sound
Set Machine: tandy
hfro t

**Comment by exoscoriae** [comment]
that downgrades the game to CGA graphics instead of EGA. And honestly, the sound doesn't sound like tandy. It sounds just like the CGA version.

I did replace some files though to enable pc speaker in the EGA version.  However, I'll need more evidence of a tandy sound version as I'm simply not hearing it.

@Python-Exoproject  - want to take a look?

**Comment by Python-Exoproject** [comment]
@bigjim161 I couldnt get Tandy sound either. Do you have an alternate version that you tested on to get the Tandy sound?

I do note though @exoscoriae that the mouse isnt working in our current version when EGA is chosen. To fix this set machine=ega. So either way, thanks @bigjim161 for getting me to look at this.

**Comment by bigjim161** [comment]
@Python-Exoproject. I think I made a mistake, I thought that by setting the conf file on "Tandy machine" the sound was in Tandy mode. In fact Exo is right, it is the same sound as CGA mode.

**Comment by Python-Exoproject** [comment]
All good. If the game had Tandy sound then that would have worked, just in this case the game only has pc speaker.

**Comment by exoscoriae** [comment]
i had already set it to ega on my end. I also changed the game files. so it all works great on my end.
