### ISSUE TITLE
Fire and Forget (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2009]
To enable music in intro use this version:
[Fire and Forget [a1] (1988)(Titus Interactive S.A.) [Action, Racing - Driving].zip](https://github.com/exoscoriae/eXoDOS/files/5286748/Fire.and.Forget.a1.1988.Titus.Interactive.S.A.Action.Racing.-.Driving.zip). Do you think the actual game runs a bit fast?

**Comment by exoscoriae** [comment]
dropped cycles to 400 and changed files.

**Comment by bigjim161** [comment]
The Exodos version has a menu with the inscription: "CRAZY CLUB". 

![image](https://user-images.githubusercontent.com/67555221/212129929-98501c7b-40a9-484c-bb3a-f021eced9ce8.png)

Maybe it corresponds to a warez group, because all the screenshots found on the web (squakenet, OG.ru, Abandonware france, My Abandonware) for this game, do not have this inscription.

![image](https://user-images.githubusercontent.com/67555221/212134617-249ec720-f4f9-4e1f-ba30-a4bd5a1cf08e.png)

Maybe we can replace it with a clean version found here: https://archive.org/details/msdos_fireforg

**Comment by exoscoriae** [comment]
replaced
