### ISSUE TITLE
Modem Wars (1988)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2021]
Can do tandy sound
set machine: tandy
war t
Execute setup.exe to make a new config file with 16 colors....

**Comment by bigjim161** [comment]
If it is not possible to play by network in tandy mode, maybe we can keep the existing mode.

**Comment by Python-Exoproject** [comment]
Another one I'm thankful you brought attention to. It seems the current conf is pointing to run.bat that doesnt exist so the game isnt running in its present state. 

I dont think adding "t" as a command line option does anything, for me just setting machine=tandy and redoing the setup was enough.

**Comment by exoscoriae** [comment]
it isn't supposed to be setup for multiplayer. Because it is dialup only. The problem seems to be games that should have been multiplayer compatible, but ended up not working out for one reason or another. As in, they are modem only and not direct connect.

I set the game up for tandy. i retried the connection system again. When selecting manual connection I can get the game to see commands from the other terminal, but once you exit the manual connect window it fails connection every time.
