### ISSUE TITLE
Black Gold (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2038]
Our current version of this game has no sound. I located a copy of the floppies in TDC and have setup a copy here: 
[blkgold1.zip](https://github.com/exoscoriae/eXoDOS/files/5318415/blkgold1.zip). The game also has separate files for a Tandy install which we dont have and although it makes no difference for sound or picture, it might be worth grabbing the installer floppies from TDC for archiving.

**Comment by exoscoriae** [comment]
hmm. the tdc files are messy at best. I went ahead and added them as it is better than nothing. But it looks like a file dump of disk1 with disk2 and disk3 in their own folders?

Also of note, the game exits immediately when using start.exe in the conf if anything is after it. pause, exit, etc... any command seems to kill it for some reason. I haven't seen this issue before.

I have yet to find a solution for this.... right now the game does not auto exit because of this.

**Comment by Python-Exoproject** [comment]
You think its worth a note to type "exit" when finished then?

**Comment by exoscoriae** [comment]
added a note before it launches. doesn't work trying to make it appear after the exit. it is almost like to continues executing the autoexec section while "start.exe" is still active.
