### ISSUE TITLE
Global Thermonuclear War (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2067]
I noted in the submission for this game to ignore the fact TDC said it was Tandy or PCJR as the colours are wrong unless you use svga_s3, however I think that note was overlooked as the game is currently using PCJR. Set to svga_s3 to fix

**Comment by AlphaHeX** [comment]
I can’t be true as S3 was introduced in ‘90 and that game is from 1985

**Comment by Python-Exoproject** [comment]
Thankyou for your input, however we realise that. Its just the standard dosbox conf setting for anything not specifically cga, tandy, pcjr, herc, etc

**Comment by exoscoriae** [comment]
as per a note from ripsaw:

"Regarding Global Thermonuclear War (1985), machine=tandy would seem to be best suited for the TDC copy because a Tandy-specific version of GW-BASIC is included. There is an issue with Tandy palette handling in 0.74, so use an SVN build. A VGA machine type like svga_s3 appears to work for getting the colors right, but the text font will be the 16-line VGA font and not the line-doubled 8-line font that is more "correct" for 1985.

It is possible to run the game with PCjr BASIC, but it involves the BASIC cartridge image and a BASIC ROM image, so it's obviously more complicated to set up than Tandy BASIC."

Setting it to Tandy as per this recommendation.

**Comment by Python-Exoproject** [comment]
Ripsaw said to use an svn build to be able to use Tandy and get the correct colours. Currently its using vanilla and has the bad colours. I tested with ECE and that worked fine.

**Comment by exoscoriae** [comment]
thanks!
