### ISSUE TITLE
Sigil (2019)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2105]
@Beylie has reported that there are two copies of Sigil in the Sigil (2019).zip archive

He has also noted that midi gain needs increasing

He has also suggested an alternate DOS port to test for high res and better sound https://www.vogons.org/viewtopic.php?f=24&t=40857&start=180

**Comment by exoscoriae** [comment]
removed the extra folder.

I went ahead and switched to this port, as it runs Sigil as the proper 5th episode, instead of replacing the 4th one.

That said, I didn't notice any options for higher res.  Better sound is questionable. technically it can support mpu-401, but it clearly sounds like a port of the original fm midi, with some switched instruments. 

I also maxed the fm gain to 1000. this was as high as I could make it. it is much better, but still a tad quieter than the normal build.

**Comment by exoscoriae** [comment]
added to updater

**Comment by Beylie** [comment]
The high-res option is in-game under options - general. 
![image](https://user-images.githubusercontent.com/28935079/98506572-76321600-2264-11eb-9e27-59ce00087720.png)

**Comment by exoscoriae** [comment]
now set to high res. thanks!

**Comment by exoscoriae** [comment]
added sc55 support and added to sc playlist
