### ISSUE TITLE
Links LS 1997 (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2145]
Loading some courses causes the game to stop responding at around 90% loaded. An example is "Castle Pines Golf Club (2000)".

Note that the game can be finicky with vesa settings for higher res if start to play around with game files.

**Comment by exoscoriae** [comment]
I've been saving this bug for last as it is the most ambiguous, and the game is just a total pain in the ass to work on due to it's size and the number of addons.

I decided to see what would happen if I started from scratch.  All files installed from the CD's work great.

https://support.microsoft.com/en-us/help/263048

According to this, Castle Pines is a much later course. It may not be backwards compatible with this version of the game.

**Comment by exoscoriae** [comment]
Ok. I reinstalled every course, cleanly, from original media. Reset all detail to max and set the resolution to 1024. It can technically go higher, but none of the in game videos were really designed for anything above 800x600. 

All courses I tested now work.

I also hard coded the values for the resort discs, so the user note has been bypassed telling users which drive they have to use to see videos. It all just works now.

Due to the size of this change, it will not be rolled into the updater unfortunately.

**Comment by bigjim161** [comment]
I found an Add-On Course - "Phoenix Country Club of Miyazaki, Japan" (USA)
This addon is not in the updated archive "Links LS 1997".

Added the Github bug folder

**Comment by exoscoriae** [comment]
this is going to be tricky, as we are already at max capacity of cds that can be loaded using imgmount w/in DOSBox at the moment.

**Comment by exoscoriae** [comment]
luckily it had no flybys or video content for LS 97. installed and works.
