### ISSUE TITLE
Crazy Nick's Software Picks (1993)

### ISSUE THREAD

**Issue by boohyaka** [exoscoriae/eXoDOS#2230]
Contains 5 Sierra-themed minigames with their individual subfolders and executables. The run.bat offers a choice to launch each one. Each game has its own resource.cfg (Sierra-style) to define drivers, and currently it's inconsistent.

- SQ and Larry have audio driver STD.DRV in resource.cfg = pc speaker
- 3 other games have ADL.DRV = adlib.

Fix is to update the resource.cfg for SQ and Larry to use ADL.DRV like the 3 other games.

To be noted that the game supports other sound options, namely Adlib/SB/PAS/Tandy 3-voice. No MT-32.

Offering a sound selection menu similar to other Sierra games could be an option, but as it's only music Adlib==Sound Blaster in DOSBox, PAS is not supported, so it would basically only offer a choice between Adlib/SB and Tandy 3-voice, so the added value is debatable.

**Comment by Python-Exoproject** [comment]
Thanks @boohyaka 

Had a look and I think I know what happened. We discovered these games had no sound awhile ago but to fix instead of changing the resource.cfg we used the play.bat file. If you type "play -?" it lists all the possible options and when you type play -s it starts the game with sound blaster. It must have been assumed that play.bat was just a simple call to scidhuv and the solution used was just to use scidhuv -s in run.bat. Turns out that play.bat calls play2.exe first which must then edit resource.cfg before loading scidhuv. We obviously used play -s on all but larry and sq, deciding at that point to not bother sunning play.bat at all.

Anyway, brief history aside, like you said resource.cfg needs editing to use adl.drv

**Comment by boohyaka** [comment]
Yep the explanation makes sense and was my own guess, as I also went through the "play ?" route to "fix" larry and noticed all it did was update resource.cfg :)

**Comment by exoscoriae** [comment]
updated resource.cfg files. rolled to updater.

**Comment by Python-Exoproject** [comment]
Put in "Add to Updater" que as not listed in the discord "exodos_updater" channel. Maybe got missed from being added to the updater?

**Comment by exoscoriae** [comment]
thanks!
