### ISSUE TITLE
Problem with SSR on exfat

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2269]
exfat has an issue with ssr that causes an issue with current loop statements. One proposed solution is to change loop to:

for /f "delims=" %%i in ('dir /b *.conf')

**Comment by exoscoriae** [comment]
Without the context of the specific discord chat, I don't remember exactly what file this loop is in.

**Comment by Python-Exoproject** [comment]
Its for the aspect ratio and widescreen/fullscreen. Something about how ssr works causing an issue inside your loops on exfat drives. Most relevant part of conversation starts here: https://discord.com/channels/454359114601201666/465909511266238474/785675483593048064

**Comment by exoscoriae** [comment]
this requires me having a way to test this. This isn't a simple syntax change. It is a change in the entire way the loop functions.

The old loop is based on dropping into each folder and checking for a conf file

the loop above is just for every conf file in the current folder. 

So, by itself it does us no good - because we *still* need the loop thatiterates through each game folder. 

And without an exfat setup to test this with, I have no idea if it actually fixes anything to take the loop above and nest it within the existing subfolder loop.

**Comment by exoscoriae** [comment]
the new options.conf solves this issue I believe, as there is no longer the need for an SSR loop during setup.

**Comment by Python-Exoproject** [comment]
True, but as we havent settled on what to do with the game installers it still happens there

**Comment by exoscoriae** [comment]
actually discussing that right now in chat. Tagged you on it.

**Comment by exoscoriae** [comment]
I'm thinking this is solved with the new launcher?
