### ISSUE TITLE
Werewolf vs. Comanche 2.0 (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2417]

**Comment by Python-Exoproject** [comment]
This issue was last discussed back in 2018 with Hamara but went nowhere. I had forgotten about it until @SmilingSpectre just brought it up again.

There was the original Comanche 2.0 release which was followed by Werewolf vs. Comanche 2.0, Werewolf was never released by itself to my knowledge. The Werewolf vs. Comanche 2.0 came with two CD's, one with Comanche 2.0, the other with Werewolf. You could install and play them separately which is what youve done in exodos.

Up until now there was just the minor issue of possible confusion  if someone launched "Werewolf vs. Comanche 2.0" and was looking for Comanche 2.0 as it isnt there. Not a huge deal as it can be still found under "Comanche 2.0" in the pack, but a small issue none the less. 

However now that we have multiplayer in the exodos pack the impact is a bit larger. With the original release you could have one person load up the Comanche 2.0 cd and another the Werewolf CD for head 2 head play using some specific H2H missions. If both players had access to a Comanche 2.0 CD or Werewolf CD they could play co-op in the main campaign missions. With our current separated setup it is only possible to play co-op without knowing that one person can install and play one game to join someone with the other.

My best suggestion is to rework the whole thing by merging a copy of our "Comanche 2.0" into our "Werewolf vs. Comanche 2.0" setup. Use a user choice menu to allow a choice between the two different single player games, and rework the multiplayer menu to allow a choice of which game to launch so players can use H2H or co-op as they desire. 

From here you could either leave the current "Comanche 2.0" alone as it was released standalone back in the day or remove it, either works. If you leave it maybe add a note to it informing that to play the same game H2H with another player in a werewolf launch "Werewolf vs. Comanche 2.0" instead?

**Comment by exoscoriae** [comment]
added comanche 2.0 cd image
added launch options for comanche 2.0 to run.bat
added ability to play against each other in network.bat
