### ISSUE TITLE
WolfPack (1990) & WolfPack Enhanced (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2424]
It has been raised by @SmilingSpectre that these two games are the same game, one the floppy release and the other a CD release. He raises the point that usually in this situation we have had one entry in eXoDOS with a user choice menu for which to play and suggests we do the same here. Heres a quote from him regarding the issue:

"Here there are two releases: floppy and CD, but while CD is technically enhanced, but just as many games before and after, it doesn't features something totally new, and Moby thinks it's the one entry. Just as publishers. So there is no release named "Wolfpack Enhanced CD" nowhere, except eXoDOS and one mention in release data of German version."

**Comment by exoscoriae** [comment]
Well, there are many games that we have to call something different, even though there was never an official name. The carmen sandiego games come to mind. They all technically share the exact same name. However, we have to call them by monikers such as "enhanced cd" or "deluxe" edition based on info taken from title screens or other sources. 

Also, moby USED to consider them separate entries, which is how it got into my database twice in the first place. They have since merged the entries because they aren't consistent with such things.

I have no problem merging them into a single entry. However there are multiple games in eXoDOS that this logic could be applied to.

**Comment by Python-Exoproject** [comment]
You merged these games as discussed but left WolfPack Enhanced in the collection even though its no longer relevant due to the merge.

**Comment by exoscoriae** [comment]
removed
