### ISSUE TITLE
Theme Hospital (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3164]
This game has MPU401 selection to enable General Midi music which is not currently setup. Setup as per usual for our GM games and add to LB playlist

**Comment by exoscoriae** [comment]
I was under the distinct impression it was unstable - like every other bullfrog game.

**Comment by exoscoriae** [comment]
I added sc-55 support to it and added it to the playlist.
I didn't extensively test, but I did load the game and get to the building part and confirm it sounded differently and was still playing at that point

**Comment by TimberlAndRE-de** [comment]
**MT-32 support**

Although you can chose MT-32 during the install process of the game (and not in the later SETSOUND after installation), it doesn't work. There's no music in the game.
The reason is, that the MT32MPU.MDI file is missing in the SOUND folder. But it's on the disc
So after manually copying the file into the HOSPITAL/SOUND folder on c:\ it works
(I guess the soundfile came with the last second before the release) 

here's the file:
[MT32MPU.zip](https://github.com/exoscoriae/eXoDOS/files/7808695/MT32MPU.zip)

**Comment by exoscoriae** [comment]
fixed mt-32 and added to playlist

nice work @TimberlAndRE-de
