### ISSUE TITLE
Microsoft Flight Simulator 1.0

### ISSUE THREAD

**Issue by exoscoriae** [exoscoriae/eXoDOS#3203]
Appears to have distortion on the main screen (instruments are not round).
Lines on the ground appear incorrect to FamiliarFez.

**Comment by SmilingSpectre** [comment]
Lines are jumping if you run the demo, (the closest end of the right line goes to far left when you drive along it) and plane goes to "Splash!" very fast because of it. It's wrong.

After some digging of TDC, I discovered that they developed the patch long ago, that fixes image (so it can be run on the "normal" DOSBox. Fun fact: it isn't implemented on the TDC game itself. So I am uploading.

1. Fixed image. (Works on ECE, in demo plane went off successfully).
2. Tool itself. Just in case. There also long explanation of the fix inside.
[Microsoft Flight Simulator v1.05 (1983)(Microsoft) [DOSBox Patch].zip](https://github.com/exoscoriae/eXoDOS/files/7034992/Microsoft.Flight.Simulator.v1.05.1983.Microsoft.DOSBox.Patch.zip)
[FS105.ZIP](https://github.com/exoscoriae/eXoDOS/files/7034993/FS105.ZIP)

**Comment by Python-Exoproject** [comment]
I believe using @SmilingSpectre FS105.zip version solves the issue, but I also recommend making this game one of our forced aspect=false as that fixes the instruments so that they are round again.

**Comment by exoscoriae** [comment]
![image](https://user-images.githubusercontent.com/8557582/130790056-b34730f8-2efb-4750-a77d-f787be310bd0.png)
this looks right to you guys?

**Comment by exoscoriae** [comment]
looks ok to me. packing it up
