### ISSUE TITLE
Indycar Racing 2 patch 1.02 and timed joystick

### ISSUE THREAD

**Issue by mgtroyas** [exoscoriae/eXoDOS#3236]
The version currently on the collection is 1.00. It has a bug that makes impossible mapping controls, it always defaults to "mouse x". Version 1.02 fixes this, also removes the yellow stripe that will appear on a car that has been painted in the IndyCar Racing 2 Paint Kit.

The patch can be downloaded from this site, but I hadn't luck applying it, seems a file (DRIVERS2.TXT) is modified from the original installation, so the patching errors out.
http://www.sierrahelp.com/Patches-Updates/Patches-Updates-Games/IndycarRacingUpdates.html

Also joystick calibration is impossible with default dosbox joystick config. The following change must be done:
timed=false
This change is needed in other games like NFS SE.

**Comment by exoscoriae** [comment]
this report is at least partially incorrect.

The readme in the game shows we are currently at v 1.0.1, rather than "1.00"

I added the timing=false flag. More research should be done one exactly which games require this. Joystick support is something I haven't spent much time on with this collection.

**Comment by exoscoriae** [comment]
updated to 1.0.2
