### ISSUE TITLE
Rogue Clone (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3772]
Spectre noted in discord:

Smiling Spectre — 14/03/2022
"Rogue Clone (1988)" is actually the fourth iteration (thus "Rogue Clone IV"). I have no idea how it differs from other versions, but it's better to have them all, I suppose (TDC have them).

**Comment by exoscoriae** [comment]
these have different developers, which would suggest they are different entries?

I've gone ahead and combined them all though, as it appears these fellows who have their names on them are not the original authors, rather just the one who made the ms-dos port of Tim Stohler's original rogue clone.

Took some finagling to get rogue clone v2 to work, due to expecting variables set to define the monitor type.

**Comment by Python-Exoproject** [comment]
Regarding V1, if you load it and press "v". It says "Version II" and "Version III", but nothing about version 1. Also the movement is a bit stuffed and if you do manage to move there is a semi-regular graphical glitch that makes your character look like its elsewhere to where it is.

V2 shares the movement issues as well

**Comment by exoscoriae** [comment]
movement works fine.

you just have to use the right keys.

H - Left
L - Right
J - Up
K - Down

The graphical glitch is something I can't do much about, assuming it is a glitch and not some weird portal spell or something.
