### ISSUE TITLE
King's Quest I - Quest for the Crown VGA (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3823]
This game can do CMS\GB and Tandy. 

Set sbtype=gb and use the cms.drv in the sierra resource file

For Tandy set tandy=on and use the tandy.drv in the resource file

**Comment by exoscoriae** [comment]
I wrote an entirely new run.bat for this that allows graphics selections as well. Might be worth doing for the other sierra games, even though it means a lot of work.

**Comment by exoscoriae** [comment]
Also renamed this to
King's Quest I - Quest for the Crown SCI (1990)
As that is a much more apt description.

**Comment by Eulisker** [comment]
I have a few comments for this. 
The game is still called KQ 1 VGA instead of SCI in the exception.bat and run.bat

![image](https://github.com/exoscoriae/eXoDOS/assets/81642149/3910fdfd-9ad1-40b2-a51e-821d3835c1b0)
![image](https://github.com/exoscoriae/eXoDOS/assets/81642149/4e15891e-5cd9-4cf0-a9ca-b1ba9418fd90)

According to John Novak on Discord the game uses EGA as a video mode. It says VGA in the run.bat and i think it should be changed.
![image](https://github.com/exoscoriae/eXoDOS/assets/81642149/2623aa2b-28d8-45c5-8612-6411ab1f2e83)

Lastly the directory for the game is \kq1vga. I don`t know if its worth the change but it could be changed to kq1sci.

**Comment by exoscoriae** [comment]
changed to "sci" in run and exception.bat files

changed all VGA references to EGA in run.bat

left folder name alone as it is destructive to change
