### ISSUE TITLE
Police Quest 1 - In Pursuit of the Death Angel VGA (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3832]
This one can do CMS\GB, or at least it should be able to. I set sbtype=gb and setup the sierra resource file but kept getting "unable to initialize hardware" error on game launch

**Comment by Python-Exoproject** [comment]
I figured it out. The resource file has separate lines for:

sounddrv=
audiodrv=

So when I had sounddrv=cms.drv I hadnt changed audiodrv=audblast.drv. This caused an issue as dosbox cant emulate both the game blaster and soundblaster at the same time. So to get cms music we need to set:

sounddrv=cms.drv
audiodrv=auddisny.drv or audiodrv=audps1.drv

auddisny is the easiest to implement, just add disney=true to the conf. I think ps1 might be marginally better but I dont think the small difference in fx quality is worth changing to X or Daum to use the ps1audio=on conf option.

**Comment by exoscoriae** [comment]
rewrote the run.bat to mimic the new style. added ega options along with new CMS options.

**Comment by exoscoriae** [comment]
also renamed game to 
Police Quest 1 - In Pursuit of the Death Angel SCI (1990)

**Comment by kcgen** [comment]
@Python-Exoproject , I wonder if a setup like this:

```ini
sbtype = sb2
oplmode = cms
```

Would work with `sounddrv=cms.drv` and `audiodrv=audblast.drv`? 

The difference here is that the card is emulated as a sound blaster with the CMS chips installed.

**Comment by Python-Exoproject** [comment]
Confirmed that option works as well, though it doesnt have to be sbtype=sb2. Thanks @kcgen.

So @exoscoriae another choice is instead of using audiodrv=auddisny.drv we can still use audiodrv=audblast.drv as long as you set sbtype=sb16 instead of sbtype=gb and set oplmode=cms.

As well as this game, Police Quest 1 - In Pursuit of the Death Angel SCI (1990), this will affect if you choose to implement the change:

Castle of Dr Brain (1991)

Quest for Glory I - So You Want to be a Hero SCI (1992) (#3863)

and once the last section of #3866 has been actioned:
Conquests of the Longbow
Mixed-Up Fairy Tales (1991)

**Comment by exoscoriae** [comment]
@Python-Exoproject  @kcgen 

so, the purpose here would be to run the FX through the blaster while retaining the CMS driver for midi?

Is the blaster quality worth making the change compared to the Disney Sound Source?

Wouldn't the Disney Sound Source be more accurate than the blaster? After all, if the user had the sound blaster... they wouldn't have been using the CMS driver in the first place.... right?  So a game blaster paired with a sound source seems like a more apt pair?

**Comment by kcgen** [comment]
Was thinking it would be handy to confirm/check if the alternative config also works - which might work in some games (and vice-versa).  Just more options in your bag.

Quality-wise:
 - On the DOSBox side, both SFX outputs (SB DAC vs. Disney)  are going to be noise-free, unlike real hardware where the SB1/2's was pretty rough; so playback quality should be on-par.
 - On the game side, the PCM samples will be same as well, leaving the game's audio drivers (Disney vs. SB DAC/DMA) being the only variable.
 - Probably a quick listening check is as that's need to confirm they're similar.

> So a game blaster paired with a sound source seems like a more apt pair?

 - Yup, definitely in the days before the sound blaster was released.

 - After the SB1 came out, users didn't need a separate PCM/DAC device (so wouldn't have needed the Disney dongle) -- plus, the SB1 came with the CMS chips -- so these users could have selected this SB + CMS configuration.
 
 - Once the SB 1.5 and 2 came out, the Creative saved money by leaving the CMS chip sockets empty, so it was a separate upgrade.  By then, CMS was already on the way out, but some users still went for the upgrade, because the two CMS chips provided 12 square-wave voices in stereo (versus the sine-wave mono OPL2 chip).  So these users might have also went with this SB + CMS choice.

Here's a user on vogons who mentioned upgrading his SB boards with CMS chips and yanking the OPL2 chip: https://www.vogons.org/viewtopic.php?t=41129&start=40

**Comment by kcgen** [comment]
CMS is pretty cool.. the two SAA-1099's can sound pretty similar to the FM chips on the NES; although the NES used one triangle wave instead of all square waves, which seems to give it a bit thicker bass sound a a better noise channel.

Here's DOSBox (Staging in this case) using [sbvgm](https://www.vogons.org/viewtopic.php?t=47059) to play NES tracks via the CMS:

https://user-images.githubusercontent.com/1557255/169910298-f0450758-0950-4dbf-b33d-1edeac3a4803.mp4

Here's a canned setup (launch dosbox inside; it'll pick up the local `dosbox.conf`), if you want to play around: [vgm-to-saa1099.zip](https://github.com/exoscoriae/eXoDOS/files/8758223/vgm-to-saa1099.zip)

**Comment by Python-Exoproject** [comment]
Yeah, as krc said, its just another option. It depends on if you want to emulate an early SB card with CMS chip onboard or a Game Blaster with Disney Sound Source. To be honest they sound pretty much the same in dosbox so its up to you, I just suggest be consistent between all the listed games

**Comment by exoscoriae** [comment]
going to leave it as is. I have enough work on my plate without going through and changing game setups for esoteric reasons.
