### ISSUE TITLE
Teenage Mutant Ninja Turtles (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3890]
Im curious on what you think about this one. Currently game is using ECE. When Tandy sound choice is selected do you think it sounds better as it is, or if switched to vanilla dosbox?

**Comment by exoscoriae** [comment]
interesting.

ece seems like the volume is too high, and it is causing the speaker to bass out. However, the samples are clearer.
vanilla has more sound depth to it due to the volume not being maxed so much, but the samples also are a lot muddier and tend to blur together.

I just tried it with x2 (a newer version of dosbox X that I included recently due to needing printer functionality I think).

I think that one sounds best out of all of them. Have a listen and let me know if you agree. 

If we keep it, I'll need to change the fullscreen setting and whatever else x2 affects.

**Comment by exoscoriae** [comment]
ok, using vanilla
