### ISSUE TITLE
Transylvania 3 - Vanquish the Night (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4079]
I noticed that the intro story is limited to the bottom part of the screen and scrolls past so that you miss it all.

I also saw that there is a sounds folder, but didnt successfully find a location in game to test if the sound was actually on\working

**Comment by SmilingSpectre** [comment]
1. It's because game initially in _graphic_ mode. Unfortunately, I see no easy workaround. Hard one is "switch to text mode with Enter and _RESTART_". Easy by wrong is pressing Enter instead name. :/
2. According to install, it's Covox. That probably wasn't set in DOSBox. I dunno where it's activated though, as initially it isn't called anywhere definitely. Well, as game load graphics during play, I wouldn't be surprised if it load sounds exactly the same way.

**Comment by exoscoriae** [comment]
the story is fullscreen for my python.

**Comment by exoscoriae** [comment]
ok, so, I played through the entire game with a walkthrough. No sound. Even tried it in a real dos boot loading the covox sound drivers the same way i set it up for last half of darkness. still nothing. In the install, both covox speech thing and covox sound master can be chosen. I tried both.

One of the sound files is called "goat". There is only one goat in the game however, and it is very near the beginning. So testing should be as simply as typing
WAIT
WAIT
WAIT
TALK DEATH

Now you are on the mountain with the goat. You can pet him and you can "GET HOBBLE" which frees him and takes you down the mountain.

Sound should be at some point in this sequence

**Comment by exoscoriae** [comment]
talked to ripsaw. He stated that there is no code in the game to actually play any of the music.... which, surprised me, since the installation specifically mentions covox speech thing and sound master.... both of which i thought were only for DOS.

So maybe they just never finished implementing the sound?

**Comment by SmilingSpectre** [comment]
There is something strange about it. Game explicitly talk about Covox. It has (c) of Covox. Moreover, during install it allows to select "no sound". Then... it installs exactly the same file set. Sounds included. 0_o. Weird.
