### ISSUE TITLE
Yumemi (1995) errors after start

### ISSUE THREAD

**Issue by Coderdreams** [exoscoriae/eXoDOS#4778]
With the SB16 option I get more crashes, with the Sound Canvas option I get further but at some point I get corruption of the image.

Way to reproduce: 

* start the game
* when a menu with numbers is display press 1 several times
* when some dialogs are displayed with kanji characters choose the 1st option
* press enter continuously to advance until it crashes

![Screenshot_20230927_001750](https://github.com/exoscoriae/eXoDOS/assets/4738090/69eb104d-e53b-423e-a4f1-922f85e1519e)
![Screenshot_20230926_233602](https://github.com/exoscoriae/eXoDOS/assets/4738090/264c5abe-3664-4ce9-a29e-68acbe13d886)

**Comment by Coderdreams** [comment]
I was able to advance by executing setup.exe in the game directory and selecting no sound. Seems the problem is the sound card emulation.

**Comment by Eulisker** [comment]
Setting another soundcard type in the .conf helped with a similar problem in a different game a while back. I will try that later today.

**Comment by SmilingSpectre** [comment]
It's DOSBox, I think. I was able to run the game with SB when tried in Staging.

**Comment by Coderdreams** [comment]
Did you continue into the game after the initial menu? I tried dosbox staging in manjaro and it doesn't go past the initial menu.

**Comment by Coderdreams** [comment]
With wine staging picking sound canvas the game works but maybe because midi fails in there:

2023-09-27 14:46:03.381 | FSYNTH: FluidSynth failed to load 'default.sf2', check the path.
2023-09-27 14:46:03.381 | MIDI: Can't open device: fluidsynth with config: '128:0'

I think the midi emulation might be the problem.

**Comment by SmilingSpectre** [comment]
Confirmed. Staging doesn't work.

But Daum works. For both SB and Sound Canvas. (Only I couldn't tune eXoDOS to specific Daum SC quirks, so it's not how it must sound).

(Can I ask stupid question: what is pure Chinese game does in eXoDOS? %)

**Comment by Coderdreams** [comment]
I don't even know, I guess most visual novels like these are in Japanese.

**Comment by Python-Exoproject** [comment]
It might be just a badly coded (or even badly cracked) game. The Staging console gave:
![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/a7360e3f-62ee-4a3f-aea6-fb406743477e)

**Comment by Python-Exoproject** [comment]
However I tried Sound canvas with Staging and didnt get a crash or error

**Comment by exoscoriae** [comment]
@Python-Exoproject

**Comment by Python-Exoproject** [comment]
Well, first question is do we keep it in eXoDOS? Its completely foreign language, I dont know what the menu choices are, I cant read the story, and I dont know what options in the game im choosing. This isnt great when the game is a visual novel.

If we keep it then the issue with the game is that for some reason (I assume bad game coding or dodgy crack) the sound blaster driver is corrupting the MCB chain. I believe Daum is working because its so loose and fast with its emulation that it can manage to stubbornly run through the errors and still work. The Sound Canvas emulation is not affected though and works fine in Staging.

We have a couple of ways we could go:

1. Delete the game as its not English playable
2. Move it to Daum (yech), giving it a daum compatible conf (Descent to Undermountain (1998) is the only game remaining on Daum so you can use it as a template for the Daum conf settings. You will also need to locate one of the old exception.bat files Daum games require for Sound Canvas emulation to work)
3. Move it Staging and remove the Sound Blaster option leaving it with Sound Canvas only. As a visual novel I dont think removing Sound Blaster is a terrible thing but I can understand why you might not like this idea.

My vote is for option 1

**Comment by SmilingSpectre** [comment]
@exoscoriae It's playable as far as any VN game playable: you have walls of texts, then text choice which can affect the further story. No good without knowing Chinese, I think.

**Comment by exoscoriae** [comment]
took option 3

the day we get a chinese language pack, we can bump it over. Until then, I dislike removing titles. It means going in and deleting entries from the xml, and that is noit something I can push in an update. So it breaks everything
