### ISSUE TITLE
Sound Issue for DOOM and other non-build engine games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4867]
A similar issue to #4862, these games do not initialise the mididevice at the beginning of run.bat which means that on the second run through if you choose to continue with the current sound card you will not have the correct sound for SC55 and MT32.

Additionally, 
- Transport Tycoon (1994) was broken and didnt launch the base game anymore, 
- Lost Episodes of Doom, The (1995) crashed if you left the menu long enough to play a demo
- Master Levels for DOOM II (1995) didnt actually load the wads as the path was wrong in the cfg file

Games that were not previously setup to use a method to keep the user setup choices that I added run.bat files for to do so:
- Boppin' (1994)
- Heretic (1994)
- Heretic - Shadow of the Serpent Riders (1996)
- Hexen - Beyond Heretic (1995)
- Hexen - Deathkings of the Dark Citadel (1996)

All the above issues fixed in this zip: [eXoDOS.zip](https://github.com/exoscoriae/eXoDOS/files/13977438/eXoDOS.zip)

**Comment by Python-Exoproject** [comment]
Also if your interested in setting them up these DOOM games do not currently have a multiplayer launch option:

DOOM 4 (2019)
Demon Gate - 666 New Levels for Doom and Doom II (1995)
Lost Episodes of Doom, The (1995)

**Comment by exoscoriae** [comment]
Demon Gate's menu has no ability to initiate a multiplayer game. Which is odd, as you can select IPX Network, # of players, and type of deathmatch from the menu. But once you launch, it goes straight to the game and does not actually try to link to anything.

DOOM 4 is a DOOM II mod. So, if you launch it's setup, you find yourself playing DOOM II networked. Only it crashes a lot because of the modifications to the engine they made. I was unable to find a way to launch DOOM 4 multiplayer.

Lost Episodes of DOOM also launches DOOM 1 when launched via setup.
 The manual talks about playing the game in multipl;ayer mode, but gives no instructions.  I suspct you have to manually call the proper wad's on command line, as the basic ipxsetup utility and the setup utility default to the standard DOOM wad.
