### ISSUE TITLE
Extra mount lines in some conf files

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4880]
Voljega discovered a few games that had extra unneeded mount commands active in the conf files.

Here are the fixes: [Fixed.Confs.zip](https://github.com/exoscoriae/eXoDOS/files/13861102/Fixed.Confs.zip)

**Comment by exoscoriae** [comment]
i disagree with changes for the sake of changes.

I removed extraneous lines manaully by using this list as a reference, but I am reluctant to touch F-15 Strike Eagle for example.

Currently, we have:
[autoexec]
mount c .\eXoDOS\f15se\floppy
c:
cls
@boot ega.img -l a
exit

His replacement is:
[autoexec]
mount c .\eXoDOS\f15se
c:
cls
@boot .\floppy\ega.img -l a
exit

I don't see how this is any better or different?

**Comment by exoscoriae** [comment]
His Kaiser Deluxe change would have blown up the game. He removed the cd mount, because at the time, the CD was missing.

I would prefer to not have someone else's fixes pushed to me like this in the future. It requires me going through and checking every single line, all because someone was trying to clean up the confs, and in the process could have broken several things.

**Comment by exoscoriae** [comment]
full metal planet: mount was fine
Marble Master: mount was fine
