### ISSUE TITLE
Wasteland (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4971]
It has been suggested to add as an option to the launch menu the reset tool provided by the developers. Discussion in Discord was here: https://discord.com/channels/454359114601201666/1183821417075179691

**Comment by exoscoriae** [comment]
remapped the mapper to F12

**Comment by exoscoriae** [comment]
denying the reset utility.

the unofficial one sucks, runs slow, and doesn't actually confirm it did anything.

the ofifical one is built into the games setup file, which doesn't even reside in the game's install folders (CGA, COMP, EGA, Tandy)

So, the game essentially has to be completely reinstalled to "reset" it. However, this means the end user would need to install it to one of the folders we already have seletcted AND set the proper video mode so that folder doesn't get borked.

Then, the diff files (assuming they are cross compatible between video modes), would have to be copied to the other install folders.

Or, if the graphics for each map are actually in the files that got reset, the utility would actually have to be run for all 4 installs.

If we used autokey or something like that it *might* be possible, but I doubt it. It would nee dto run 4 times, and each time it runs we would need the proper timing built into it to ensure the auto keys don't get lost. And we have to rely on the end user not pushing anything.

For all of these reasons, I feel this is not worth it.

**Comment by Python-Exoproject** [comment]
There is an errant pause in the `:ega` section of run.bat

Also, the cycles are way to fast at 6000, I think 600 is better as now the mouse isnt super fast and when you are moving with the mouse inside locations it moves one square at a time instead of zipping halfway across the screen

**Comment by exoscoriae** [comment]
xavier velo was the one who suggested 6k I believe. he has very strong thoughts on how this game should run.

i dropped it back to 600 per your suggestion.

removed pause as well. good catch.

**Comment by XavierVelo** [comment]
Nope, wasn't me. My suggestion was 700, where game's playable with mouse.
