### ISSUE TITLE
Lite-Version download not showing all file sizes

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4984]
Lite Version v6:

The installer asks if you want to download the game and then displays the estimated download size. However, the new second zip for the metadata is not taken into account yet. I guess it's not a big deal, but it should probably be corrected at some point so that it shows both download sizes. This can be irritating for games that are only one MB in size but have 100 MB of extras.

**Comment by exoscoriae** [comment]
![image](https://github.com/exoscoriae/eXoDOS/assets/8557582/7abd01c4-1e47-49dc-87e8-700c27673c95)

I have added this

I can't really add the two values together, as that is a major headache in batch. Specifcally because some games are calculated in KiB and some are in MiB. So to add them would require not only trimming away all of the excess spaces and such, then going in and removing all commas, but also tracking the unit of measurement and doing conversions to add them together.

The conversion part would actually be easy compared to distilling the value down to a number that can be added in batch (use set /a)

**Comment by exoscoriae** [comment]
ok, I went back and kept working this. Now it is much smart and shows combined download size.
