### ISSUE TITLE
Lands of Lore - Guardians of Destiny (1997) - Fixes inc Memory Allocation error

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5055]
This journey started by a bug report from hunvagy in discord reporting that the game crashed during a characters conversation.

After investigating I found it to be the presence of the 3dfx driver causing a memory allocation error in both 3dfx and non3dfx choices. Some further research discovered that the issue wasnt unknown online and there was no fix, only a workaround. It was further investigated on the staging github (https://github.com/dosbox-staging/dosbox-staging/issues/3481) and later confirmed by boohyaka to be an issue even on real hardware.

I also found that our setup of the game was wrong. As currently released all sound options actually output CD Audio Digital music instead of their midi. This probably happened because the midi\digital setting is kept in the same game options file as the 3dfx on\off setting.

Lastly, it was raised that the difficulty was overwritten anytime you started the game as the setting is saved in the ini files.

I have come up with a solution to all of the above issues. On request ive also changed the game so that instead of starting in game it starts on the main menu so you can easily load your previous save or start a new game. Ive also converted the game to Staging while I was working on it as its a 3DFX game and staging implementation of 3DFX is better (faster, not restricted to original 3DFX resolutions). 

Please change game to staging in dosbox.txt ~~and use the files in this archive: LLGD.zip~~

Edit: Thanks to the below information and fix from @kjliew this issue is now fixed in the game files and a workaround is no longer required. Please use the files provided here instead of those above: [LLGD.zip](https://github.com/exoscoriae/eXoDOS/files/14559854/LLGD.zip)

Once implemented the folders \LLGD\WESTWOOD\LOLG3D\norm and \LLGD\WESTWOOD\LOLG3D\3dfx are no longer needed

**Comment by kjliew** [comment]
>Some further research discovered that the issue wasnt unknown online and there was no fix, only a workaround. It was further investigated on the staging github (https://github.com/dosbox-staging/dosbox-staging/issues/3481)

**A simple fix to 3Dfx DOS Glide Land of Lore 2 is available** at:
https://github.com/kjliew/qemu-3dfx/issues/20#issuecomment-1984851882

**Comment by Python-Exoproject** [comment]
Thanks @kjliew for both the fix and taking the time to bring it to our attention. Its worked like a charm so far

**Comment by kcgen** [comment]
Just checking in (nice work!); wanted to pass on a couple other fix alternatives (using the original executable):

Increase the Voodoo's RAM size, like you suspected @Python-Exoproject:

 - `voodoo_memsize = 12`; no other change is needed. This is Staging-specific though.

Another option is letting the game use 60+ MB of real RAM, instead swapping half the memory to the HDD:

1. set `[dosbox] memsize = 64` in the game's `dosbox.conf`
2. Place [**`lolg.vmc`**](https://github.com/exoscoriae/eXoDOS/files/14563573/LOLG.VMC.ZIP) beside `LOLG.EXE`, and add `set DOS4GVM=@LOLG.VMC` in `WESTWOOD/LOLG3D/run.bat` before running the game.

(This compatible with all DOSBoxes and machines/VMs with 64+ MB of RAM).

---

Swapping the CDROMs (Ctrl+F4) can also be avoided by performing  a full install of the data files.
- You can do this by manually copying `*.MIX` from each CDROM into `WESTWOOD/LOLG3D`
- Or use DOSBox to run [**`fullinst.bat`**](https://github.com/exoscoriae/eXoDOS/files/14563703/fullinst.bat.zip) in the game's top-level `LLGD` directory, which performs the copy as a one-time task and will skip on subsequent runs.
- With the data files installed, update `WESTWOOD/LOLG3D/run.bat` with new launch statements: `@LOLG -CD .`, which tells the game to find the data files in the current directory instead of labelled CDROMs.

**Comment by johnnovak** [comment]
That's some Staging wiki worthy material there @kcgen 🎖️ I'll add it today.

**Comment by kjliew** [comment]
>Increase the Voodoo's RAM size, like you suspected @Python-Exoproject:
>- voodoo_memsize = 12; **no other change is needed**. This is Staging-specific though.

@kcgen What a nice timing at checking in😜. Don't you also have such a **_Code of Conduct_** of STOP⛔ spewing the **\*BS\*** ?🤣🤣 Did you check it out on Staging?? There is nothing specific for Staging about `'voodoo_memsize'`. That basically realizes a beef-up never-existed voodoo1 config of 4MB FBI + 2x 4MB TMU but supported in MAME source code. Everyone else that do voodoo emulation also have it, including **whatever "Trash"Boxes or "JUNK_PC"em** from which do not source their implementation from MAME source code. However, it has nothing to do here nor increasing voodoo memory could have fixed anything. Otherwise, the QA folks at Westwood Studio could have been the aliens from another timeline of parallel universe where 3Dfx never went busted, and they brought with them such "special" voodoo1 for their in-house playthrough in 1997.

Nice one for the DOS4GVM tweaking though, for having the game in 👍**pristine condition**👍. I guess the QA folks at Westwood Studio must have been masters of DOS4GVM memory management to have this bug slipped through into releases.

@johnnovak I wonder if you'll also remove the following snippet from "Non-goals" of DOSBox Staging worthy of honoring the **_Code of Conduct_** of STOP⛔ spewing the **\*BS\*** ?🤣🤣
https://dosbox-staging.github.io/about/#non-goals (specifically 2nd sentence)

![image](https://github.com/exoscoriae/eXoDOS/assets/56374095/e4c49166-de9d-4727-88e1-7b52bb25fccc)

As none of those in the **highlighted** of **whatever "Trash"Boxes or "JUNK_PC"em** are examples of cycle-accurate emulators.

**Comment by johnnovak** [comment]
@kjliew Get professional help.

**Comment by johnnovak** [comment]
@kcgen [lolg.vmc.zip](https://github.com/exoscoriae/eXoDOS/files/14563573/LOLG.VMC.ZIP) seems to be broken, could you please upload it again?

**Comment by kjliew** [comment]
@johnnovak Thank you. I am just following @kcgen inspired excellence [**_Code of Conduct_**](https://github.com/kcgen/inspire-excellence-coc/blob/main/CODE_OF_CONDUCT.md#code-of-conduct) in **_"educate and illuminate"_** the TRUTH. Don't you think it is a laughing shame for [dosbox-staging](https://dosbox-staging.github.io/about/), a professionally developed project with modern C++ standards, static analysis and meson build system, to include such **\*RETARDED\*** lies of **_"cycle-accurate"_ Accuracy \*BS\*** in "About DOSBox-Staging Non-goals"?

Or would you rather believe when LIES were told a thousand times would have become the TRUTH🤣?

**Comment by Python-Exoproject** [comment]
@kjliew I am very appreciative of your coming up with a fix and bringing it to our attention, but this is a ticket about fixing the Lands of Lore Guardians of Destiny game and not for personal discourse. For that reason I deleted your comments, but am happy for you to repost anything relating to the game or its fix.

I am not taking sides in anything by doing this, I just want to keep the ticket clean for others to use as a reference to fix the game

**Comment by kcgen** [comment]
> @kcgen [lolg.vmc.zip](https://github.com/exoscoriae/eXoDOS/files/14563573/LOLG.VMC.ZIP) seems to be broken, could you please upload it again?

Oh, thanks for flagging this @johnnovak - re-uploaded (in the original comment; direct link here: https://github.com/exoscoriae/eXoDOS/files/14566651/LOLG.VMC.ZIP)

**Comment by Python-Exoproject** [comment]
@kcgen I tested the voodoo_memsize solution and it didnt work for me, however the vmc method I can confirm works.

**Comment by Python-Exoproject** [comment]
@exoscoriae Ill leave the decision on adding the CD data to the HDD so that disc swapping is not required up to you as on one side this makes it easier for the user as they dont need to swap discs, but on the other as we include the CD media it means duplicating the data

**Comment by kcgen** [comment]
> @kcgen I tested the voodoo_memsize solution and it didnt work for me, however the vmc method I can confirm works.

Ahh, my bad @Python-Exoproject - I had mixed this up with another fix (rename LOLG.DAT to LOLG.EXE, and backup the original .EXE). Editing my comment to snip this suggestion :-)

**Comment by kjliew** [comment]
> @kjliew I am very appreciative of your coming up with a fix and bringing it to our attention, but this is a ticket about fixing the Lands of Lore Guardians of Destiny game and not for personal discourse. For that reason I deleted your comments, but am happy for you to repost anything relating to the game or its fix.
> 
> I am not taking sides in anything by doing this, I just want to keep the ticket clean for others to use as a reference to fix the game

Ahh, my bad @Python-Exoproject - I hoped they won't simply close the issue next time as the same issue applies on real hardware. In **TRUE spirit of Game Preservation**, the emulators have the edge of debugging visibility how it failed. I am pretty sure @kcgen and @johnnovak had read it and they got the messages. It's ALL about the games😜, WTF about DOS emulator if it can't play Land of Lore 2 Guardians of Destiny in full 3Dfx glories?!🤣

Unlike many other emulation projects, the [qemu-3dfx project](https://github.com/kjliew/qemu-3dfx) takes pride in besting any period-correct, real hardware on Game Preservation with peace-of-mind isolation for retro gaming, and **absolutely NO Accuracy \*BS\***.

**Comment by exoscoriae** [comment]
@kjliew your reply continues to not be related to this topic. 

I sincerely appreciate your help with this issue. I would really like to continue benefiting from your expertise on issues such as this 

That said, @Python-Exoproject was very clear that anything off topic has no place here. I honestly don't care what went down on another projects GitHub or discord server or anything else. 

Please refrain from continuing to use my github as a place to discuss your issues with other projects. I really don't want to have to ban or mute anyone. 

Thank you.

**Comment by exoscoriae** [comment]
ok... well

runs from HD now
has mem 64 fix
fixes from the top were applied as well

**Comment by Python-Exoproject** [comment]
Best this game has ever worked. I did make a typo in the run.bat though, "Miscelaneous Controls" should be "Miscellaneous Controls"

**Comment by exoscoriae** [comment]
repacking a 4gb game because of a typo.

i hate today
