### ISSUE TITLE
Indiana Jones and The Last Crusade (1989)

### ISSUE THREAD

**Issue by boohyaka** [exoscoriae/eXoDOS#5065]
![image](https://github.com/exoscoriae/eXoDOS/assets/31538990/6722d9fc-3508-48c2-99f7-ed2eff81bcd8)

IndyCru\run.bat:

- Option 1 runs with PC-Speaker. INDY3 EGA did not support gameblaster, support was added in the VGA version
- Option 1 could be replaced by Tandy in the same menu, by calling the patched executable that bypasses hardware validation. Dosbox.conf just needs to set tandy=on and sbtype=none. This can be called from within the batch itself
- Detail, but SoundBlaster options could be renamed to AdLib for precision. There is no real Sound Blaster support in either version
- a "goto quit" is missing for the :CMS option

Anyway I'm attaching my fixed run.bat proposal, and the patched executable for tandy sound that needs to go in IndyCru\EGA

[files.zip](https://github.com/exoscoriae/eXoDOS/files/14593940/files.zip)

**Comment by exoscoriae** [comment]
sounds good. all changes accepted and added

**Comment by Python-Exoproject** [comment]
The run.bat was using an invalid value for sbtype (sbtype=default) and the setting (along with the mididevice) was not necessary anyway so I cleaned it up since I had it open. I also provide a conf to flick the game to Staging as I think we plan on moving all Tandy\PCjr games to Staging eventually

[IndyCru.zip](https://github.com/user-attachments/files/16114627/IndyCru.zip)

**Comment by exoscoriae** [comment]
ok. done... again
