### ISSUE TITLE
ScubaVenture The Search For Pirate's Treasure (1993)

### ISSUE THREAD

**Issue by TheKins** [exoscoriae/eXoDOS#5081]
Should probably be switched in dosbox.txt from vanilla dosbox.exe to ece4230\dosbox.exe for more accurate PC Speaker emulation. Was also having some joystick/key mapper issues in vanilla dosbox that changing the build fixed, but that's probably less relevant. :)

(I used ece4230 because it was the same build used by Duke Nukum 1, another game that leans heavily on PC Speaker noises that vanilla dosbox doesn't reproduce so well)

**Comment by Python-Exoproject** [comment]
Hi @TheKins thanks for the report.

For alt launcher to get the sound benefit be this game will need to be switched to Staging for main launch instead of ECE. Use: [conf.zip](https://github.com/exoscoriae/eXoDOS/files/14731550/conf.zip)

I note @TheKins you also list Duke Nukem, and I also know about Commander Keen. Do you know of any others that I will need to add to the review list for alt launcher compatibility for this reason?

Background on why Staging switch required instead of just using ECE for those interested: Vanilla dosbox, Daum, and I think X use a method for pc speaker emulation that the Staging guys call 'discrete'. The emulation code advanced over time and even when using discrete method the pc speaker sound is better in X and Staging than it is in Vanilla in all cases. There is another approach though that the Staging guys call 'impulse'. This is the method used by ECE and is needed by a small number of games to play the pc speaker sound properly. It has been discovered though that impulse cannot be used as the new standard like ECE forces, as some games have a problem with this method and wont play speaker sound properly when used. For this reason the Staging guys offer both methods, switching between them with a conf setting (pcspeaker=discrete (default) and pcspeaker=impulse). This is good news as it provides options but means any game that needs the impulse method for sound needs to be switched to Staging so that the conf includes the pcspeaker=impulse value and the alt launcher can also benefit.

**Comment by TheKins** [comment]
> you also list Duke Nukem, and I also know about Commander Keen. Do you know of any others that I will need to add to the review list for alt launcher compatibility for this reason?

A lot of the Apogee and Id Software games that used or had an option for PC speaker, really. Cosmo's Cosmic Adventure, Wolfenstein 3D, Bio-Menace, etc. etc. all had a lot of complicated PC Speaker sounds that the Discrete emulation doesn't do so great a job with.

**Comment by exoscoriae** [comment]
switched to staging.

thank you @TheKins & @Python-Exoproject

**Comment by Python-Exoproject** [comment]
Wrong Scubaventure game switched in dosbox.txt, this is the 1993 game and the 1983 one got switched. 1993 game is in folder \ScubaSPT

This also broke the 1983 game as the conf was replaced with the one intended for the 1993 game

**Comment by exoscoriae** [comment]
restored 83 conf

fixed 93 conf

fixed txt file

**Comment by Python-Exoproject** [comment]
Through all this it seems I didnt actually set the needed setting in the conf, not sure how I did that.

To finally finish with this one please change in the conf:

pcspeaker=discrete

to 

pcspeaker=impulse

Sorry for the oversight

**Comment by exoscoriae** [comment]
done. good catch
