### ISSUE TITLE
In Extremis (1993)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5083]
User @TServo2049 noticed that In Extremis is a fan-translated version. Seems so for me too. So I uploaded TDC's multilanguage version.

In Extremis (1993) Multi-Language.zip

It contains:

- [ ] Fixed game (seems it's protected or something)
- [ ] Vanilla installer
- [ ] Floppy images

**Comment by Python-Exoproject** [comment]
This game was on my radar as the sound blaster output has pops at the end of every effect while the covox sound doesnt and is just as good otherwise.

Ive used Spectres installer to install the official English version, setup the game to use Covox, included the Staging conf as ive been moving all the covox games over to Staging for reasons discussed in other tickets, and added two text files in the "Extras" folder that include game tips and level codes. The game tips file also lists the level code for the first level as this is given in the game manual (which is in French) and is needed to use any wall consoles in the game for the first level.

The old version we had has a popup randomly appear saying the game is cracked by Randal Flag (who has helped us crack some of our other previously uncracked games) but im not sure what it is cracking as the official English version seems to be working ok.

Use the files in this zip ([In_Extremis.zip](https://github.com/exoscoriae/eXoDOS/files/14823633/In_Extremis.zip)) and set to launch with Staging 81.1

**Comment by exoscoriae** [comment]
fixed
