### ISSUE TITLE
Blues Brothers, The (1991)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#5089]
A couple of notes on this one. 

Until gameplay starts this game runs agonizingly slow. It takes forever loading the character select screen and the Brothers should dance faster in there. Switching it to staging does solve the issue. 
You can activate sound effects by pressing F3. You have to do this every time you start the game. Maybe have a small text at the beginning mentioning this?

**Comment by SmilingSpectre** [comment]
Hmm. Looks like everyone has the same hacked version where something went wrong.

Original goes through keydisk though, so I cannot check if it behave the same.

Reissue on CD has sound enabled right from the start... but it's EGA only.

Only exe differs otherwise, btw. 
[BLUES.ZIP](https://github.com/exoscoriae/eXoDOS/files/14843297/BLUES.ZIP)

**Comment by exoscoriae** [comment]
moving to staging appears to fix the timing issues.

added the blues.exe file anyways, and repointed the conf to it
