### ISSUE TITLE
Falcon Gold (1994)

### ISSUE THREAD

**Issue by interloper98** [exoscoriae/eXoDOS#5161]
The current settings cause the intro FMV dog fight audio to play earlier than the video. This problem plagued real hardware, too:

> _[@damsonn](https://www.youtube.com/@damsonn) Falcon 3 intro was always CPU dependent (as well as scrolling campaign update text crawl). On my actual Pentium 75MHz it ran too fast back in the day too, so it's not the emulation fault_

However, YouTube DOS sim gamer @darkendroom has come up with some `dosbox.conf` settings that get the intro FMV timing correct *and* the in-game play timing very fluid using DOSBox Staging 0.81.1:

Intro: 

https://github.com/exoscoriae/eXoDOS/assets/165201780/9b5de42d-4fda-453e-a207-87bd60dd3e2a

In-game (same settings):

https://github.com/exoscoriae/eXoDOS/assets/165201780/d109bd79-a964-4f23-806e-e02c0190db65

The settings he's using are in the video description box https://www.youtube.com/watch?v=6xXv2UuhOtc

**Comment by interloper98** [comment]
Oh, he also runs a blog where he posts optimal DOSBox settings (many of them starting to use DOSBox Staging), fixes, and tweaks.  

He takes great care to get the game play optimal, very much like eXoDOS. It might be worth while 'mining' it:

 https://www.tales-from-darkenedroom.com/my-blog

**Comment by Python-Exoproject** [comment]
I wasnt even aware there was a speed issue with the game, so thanks for the report and highlighting that blog, def worth a look.

My issue with the settings when I tried them was that the intro sound gets all garbled, that very first sound that is unidentifiable in the video you attached is a bird chirping when you arent using vmem_delay. I played around a bit with the dos_rate and vmem_delay but couldnt find a combination that both improved the sync and didnt screw the sound or make the planes jitter across the sky.

One thing your report has highlighted though is that our current cycles of 25000 is way to high for the gameplay, you cant even read the theatre intro when you start a campaign it goes so fast. Reducing cycles to 8000 seems to slow the briefing down to a readable speed and still be smooth during gameplay. The intro is still out of sync but at least its only the intro, these speed issues are not uncommon with the worst being Privateer 2 but in that games case the whole game is unplayable in dosbox thanks to the issues.

If using the copy in eXoDOS you find some setting that are able to a) sync the intro without affecting the sound, b) not jitter the planes all over the sky, and c) still have briefings and gameplay at a useable speed then please let me know and ill be happy to review again.

For now @exoscoriae I recommend changing the cycles to 8000 in the dosbox.conf in order to resolve the briefing being to fast for two games in this Falcon Gold collection, Falcon and Hornet. See below for the third game in the pack Mig-29.

It seems Mig-29: Deadly Adversary suffers the same campaign briefing issue, however 8000 cycles causes the intro to become unresponsive if it is allowed to start playing. The minimum cycles that the intro will work on is 14000 leaving us a choice of using 8000 and telling the user to skip the intro at the Spectrum Holobyte logo or using 14000 and having the briefing to fast to read. If you go with 14000 we can make the change in run.bat so that the other two games can still use 8000

**Comment by interloper98** [comment]
If I find something better, I will let you know. 

Your suggestion is a very nice improvement as the briefings are critical to play through a campaign. Thanks for this, @Python-Exoproject.

**Comment by exoscoriae** [comment]
reduced to 8k cycles in the conf
add CONFIG -set "cycles=14000" to the Mig-29 lauch entries... seems better then telling a user they have to skip the intro.

**Comment by Python-Exoproject** [comment]
Ive now created an 86box launch option for Falcon Gold that resolves all these speed issues.

Please find the required files in the usual location, `sync\GitHub\eXoDOS\Game Submission\Python`

**Comment by exoscoriae** [comment]
I'll add it whenever it actually shows up in my sync

**Comment by exoscoriae** [comment]
added
