### ISSUE TITLE
Quake (1996)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5184]
Our manual is a very bad quality. Here are two others, one is slightly better, second is quite good - but multi-language and quite big.

- [ ] Quake (1996).pdf
- [ ] Quake (1996) (En, De, Fr, Sp, It, Du).pdf

**Comment by TimberlAndRE-de** [comment]
my thought about them:
While our current manual is too brightened so the page background is just slightly visible I think the first one isn't really better because it has those moiré scan lines...
And the second one is from the European release (while ours is from the US release).

I guess we let eXo decide ;-)

**Comment by exoscoriae** [comment]
going to keep the original for now

**Comment by Eulisker** [comment]
I rescanned the manual and uploaded it again. I also made a short version with just the english parts. The content is the same as in the current manual. Only the back page is different because it has the UK address of the publisher on it.
