### ISSUE TITLE
Realms of Arkania - Blade of Destiny (1992)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5272]
Please replace the run.bat file with the one in the attached zip archive. This fixes a Linux mounting issue without needing a separate file.
[rarkani1_fix.zip](https://github.com/user-attachments/files/16169606/rarkani1_fix.zip)

**Comment by parricc** [comment]
This file has not been modified since 2023-08-10. As such, I assume eXo will want to maintain two sets of files rather than merging it into the main zip and causing people to download a new one. The following zip contains the correct filename to create a Linux update file: 
[rarkani1_linux_fix.zip](https://github.com/user-attachments/files/16444997/rarkani1_linux_fix.zip)

**Comment by exoscoriae** [comment]
added to update file

in general, I am not interested ina dding any of these files to the base version. I try not to add files if I don't have to. it's not good rpeservation to fill them with our own content. I would love to host my own run.bat files elsewhere instead of in the zip, but I don't have a good solution for that without repacking everything and creating thousands of new files.
