### ISSUE TITLE
Red Dawn (1998)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5292]
Please add the `run_lin.bat` file and replace the `run.bat` file with the one in the attached zip. The `run.bat` file fixes the game directory references (was originally referring to `comconra`). Then, the `run_lin.bat` file contains Linux fixes.
[ccrard_fix.zip](https://github.com/user-attachments/files/16197436/ccrard_fix.zip)

**Comment by exoscoriae** [comment]
fixed

**Comment by Python-Exoproject** [comment]
My sync has two copies of this game zip, one called `Red Dawn (1996).zip` and another `Red Dawn (1998).zip`. The 1996 one got updated with the new run.bat.

**Comment by exoscoriae** [comment]
I have no idea where that 1996 version came from. I deleted it

**Comment by Python-Exoproject** [comment]
Confirmed, but the run.bat in the copy kept still references cd images from another game. This game is in folder ccrard while the image path in run.bat is comconra. 

To be honest im not even sure why the cd mount lines exist in run.bat as they are doing nothing since the d drive already has a cd mounted via the conf. All it does is cause issues for Linux (unless that was the plan :wink:)

**Comment by exoscoriae** [comment]
removed lines from run.bat file..

no idea why it was in both places either

**Comment by parricc** [comment]
Going to reopen this and assign it to myself as a reminder to verify the changes and see whether a run_lin.bat file is still needed.

**Comment by parricc** [comment]
This game no longer needs a `run_lin.bat` file. @exoscoriae Please remove the Linux update file for Red Dawn (1998).

**Comment by exoscoriae** [comment]
removed
