### ISSUE TITLE
Blood (1997)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5293]
Please replace the run.bat file with the one in the attached zip archive. This fixes a Linux mounting issue without needing a separate file.
[Blood_fix.zip](https://github.com/user-attachments/files/16197766/Blood_fix.zip)

**Comment by exoscoriae** [comment]
update created

**Comment by parricc** [comment]
The modifications were in a `run.bat` file, not a `run_lin.bat` file. This was done to avoid maintaining two sets of files. As such, it needs to be merged into the main zip rather than a separate Linux update.

**Comment by parricc** [comment]
@Python-Exoproject As we discussed, this game also has 3dfx issues due to problems in the `run.bat` file, which you have worked into an updated version. Please merge the changes from this ticket into that fix:

The following lines need be changed:
`if exist CD.SEL imgmount d ".\eXoDOS\Blood\cd\bloodcd1.cue" -t cdrom`
`imgmount d ".\eXoDOS\Blood\cd\bloodcd1.cue" -t cdrom`

To the following:
`if exist CD.SEL imgmount d C:\cd\BLOODCD1.cue -t cdrom`
`imgmount d C:\cd\BLOODCD1.cue -t cdrom`

The changed method of mounting the images works for this game in both Windows and Linux, eliminating the need to maintain two sets of files. After merging the changes, please ensure there is no Linux update file for Blood in WIP.

**Comment by Python-Exoproject** [comment]
Ok. Ive done so and provide the required files to make this change (confirmed working) along with fixing an error when launching the 3dfx version without changing sound card and converting to the much better Staging 3dfx implementation.

Please convert to Staging and use these files: [eXoDOS.zip](https://github.com/user-attachments/files/16408945/eXoDOS.zip)

For more info on the issue when launching 3dfx without having changed sound card keep reading:

We solved the users control preferences not being universal by copying in the blood.cfg file to each of the sub games as it was identical for each game, which worked great for all the non 3dfx launch options. When launching the 3dfx choice it turns out though that the non-3dfx blood.cfg file has resolution settings incompatible with 3dfx mode which was causing 3dfx mode to crash. 

This meant to fix the 3dfx crash we needed to change those resolution setting in blood.cfg while keeping the rest of the file so that the user keeps their control config. SSR wasnt an option as we are inside dosbox runtime at this point and I couldnt get working setlocal delayed expansion with a for loop inside dosbox.

I found a DOS era util that worked and might be worth keeping in your toolbox called mtr. Ive included it and a DPMI mode TSR that it needed to run in the files along with an updated run.bat that makes the needed file change when 3dfx mode selected.

**Comment by exoscoriae** [comment]
> The modifications were in a `run.bat` file, not a `run_lin.bat` file. This was done to avoid maintaining two sets of files. As such, it needs to be merged into the main zip rather than a separate Linux update.

no. I am not updating games.

**Comment by exoscoriae** [comment]
In this case I have replaced the files in blood because they actually address an issue with windows in regards to 3dfx.
