### ISSUE TITLE
Pro Pinball - Timeshock! (1997)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#537]
page 2 is missing

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found an alternate version with all pages except the front and back pages
since the current one also has a wrong frontpage, it can't be used so this pages are still missing
but since the content part of the manual is complete, it should be replaced by Spectres Version

also there are two manuals , a table manual (this one) and a technical manual, proof:
![grafik](https://user-images.githubusercontent.com/67441153/89738745-54fe3580-da7b-11ea-83cd-85093f98c432.png)

**Comment by exoscoriae** [comment]
I don't understand the notion that the current one "has the wrong front page". It looks pretty official to me. Just because the release in the picture had two different manuals doesn't mean there wasn't a later release that combined them into a single manual.

I inserted the "missing" page 2 from Spectre's version into the existing one and threw the rest out.
