### ISSUE TITLE
Les Manley in Search for the King broken

### ISSUE THREAD

**Issue by Dutchmagic** [exoscoriae/eXoDOS#5527]
6.04 eXoDOS release breaks almost at the end of the game.
The game is also not cracked and the "parts catalog" is missing from the manual.
The attached file needs to be replaced to fix the crash (thanks @SmilingSpectre). 
Parts Catalog should also be added so people can look up the answers for the copy-protection. 
[DATAE.zip](https://github.com/user-attachments/files/18169776/DATAE.zip)

**Comment by SmilingSpectre** [comment]
Correction: we have parts catalog since 2022. And TDC has cracked exe, if needed. And the whole cracked v2.0 (I dunno if it's better than our 1.0).
[Les Manley in- Search for the King v1.0 - Hacked EXE.ZIP](https://github.com/user-attachments/files/18171430/Les.Manley.in-.Search.for.the.King.v1.0.-.Hacked.EXE.ZIP)
[Les Manley in- Search for the King v2.0 (1990)(Accolade, Inc.) [Adventure].zip](https://github.com/user-attachments/files/18171431/Les.Manley.in-.Search.for.the.King.v2.0.1990.Accolade.Inc.Adventure.zip)

**Comment by exoscoriae** [comment]
replaced with 2.0 files
