### ISSUE TITLE
Tornado (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#999]
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found a photographed version of the manual
So quality isn't good but it has a lot more pages (+260) and information than current one

- [ ] manual (photographed, more pages, more information relevant for playing the game)

added to the github folder

**Comment by exoscoriae** [comment]
index of the "smaller" manual has all of the same sections. The lower quality manual is def more pages, but that seems to be because the higher quality manual has more information *per page*.

I saw no actual information in the lower quality manual that was not present in the higher quality manual when I went through each section.

**Comment by exoscoriae** [comment]
replaced
